"""Categories many to many

Revision ID: 04030e1bb93e
Revises: 817ac39e1481
Create Date: 2024-11-14 17:33:02.417071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04030e1bb93e'
down_revision = '817ac39e1481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_categories')
    # ### end Alembic commands ###
