"""Main category and subcategory tabled added

Revision ID: 1eed8f2b0c6e
Revises: 25682652ccb4
Create Date: 2024-11-13 22:29:28.559418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eed8f2b0c6e'
down_revision = '25682652ccb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('main_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_main_categories_name'), ['name'], unique=False)

    op.create_table('sub_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sub_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_categories_name'), ['name'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maincategory_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subcategory_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'main_categories', ['maincategory_id'], ['id'])
        batch_op.create_foreign_key(None, 'sub_categories', ['subcategory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subcategory_id')
        batch_op.drop_column('maincategory_id')

    with op.batch_alter_table('sub_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_categories_name'))

    op.drop_table('sub_categories')
    with op.batch_alter_table('main_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_categories_name'))

    op.drop_table('main_categories')
    # ### end Alembic commands ###
