"""Main category removed

Revision ID: 25682652ccb4
Revises: c25b3d5be4f7
Create Date: 2024-11-13 22:25:42.385864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25682652ccb4'
down_revision = 'c25b3d5be4f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('maincategory')
        batch_op.drop_column('subcategory')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('maincategory', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
