"""product table

Revision ID: 50bda5527a1b
Revises: 8a319a8207da
Create Date: 2024-11-09 23:28:09.892438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50bda5527a1b'
down_revision = '8a319a8207da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('size', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('ean', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('ean')
        batch_op.drop_column('weight')
        batch_op.drop_column('size')
        batch_op.drop_column('ingredients')
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
