"""Main category and subcategory tables removed

Revision ID: 646010facfc2
Revises: 1eed8f2b0c6e
Create Date: 2024-11-14 12:37:26.937246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '646010facfc2'
down_revision = '1eed8f2b0c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    # Drop foreign key constraints
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_ibfk_4', type_='foreignkey')
        batch_op.drop_constraint('products_ibfk_3', type_='foreignkey')
    
    # Check if the index exists before attempting to drop it
    result = conn.execute(text("SHOW INDEX FROM sub_categories WHERE Key_name = 'ix_sub_categories_name'"))
    if result.fetchone():
        with op.batch_alter_table('sub_categories', schema=None) as batch_op:
            batch_op.drop_index('ix_sub_categories_name')

    op.drop_table('sub_categories')
    
    result = conn.execute(text("SHOW INDEX FROM main_categories WHERE Key_name = 'ix_main_categories_name'"))
    if result.fetchone():
        with op.batch_alter_table('main_categories', schema=None) as batch_op:
            batch_op.drop_index('ix_main_categories_name')

    op.drop_table('main_categories')
    
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('subcategory_id')
        batch_op.drop_column('maincategory_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maincategory_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subcategory_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('products_ibfk_3', 'main_categories', ['maincategory_id'], ['id'])
        batch_op.create_foreign_key('products_ibfk_4', 'sub_categories', ['subcategory_id'], ['id'])

    op.create_table('main_categories',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('main_categories', schema=None) as batch_op:
        batch_op.create_index('ix_main_categories_name', ['name'], unique=False)

    op.create_table('sub_categories',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sub_categories', schema=None) as batch_op:
        batch_op.create_index('ix_sub_categories_name', ['name'], unique=False)

    # ### end Alembic commands ###