"""subcategories3rd removed

Revision ID: 817ac39e1481
Revises: 3432479b125c
Create Date: 2024-11-14 17:29:02.661538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '817ac39e1481'
down_revision = '3432479b125c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_ibfk_4', type_='foreignkey')
        batch_op.drop_column('third_subcategory_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('third_subcategory_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('products_ibfk_4', 'categories', ['third_subcategory_id'], ['id'])

    # ### end Alembic commands ###
