"""Order table for Stripe

Revision ID: 84273fec0557
Revises: d749d8eff427
Create Date: 2024-11-15 12:13:28.084756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84273fec0557'
down_revision = 'd749d8eff427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [column['name'] for column in inspector.get_columns('orders')]
    with op.batch_alter_table('orders', schema=None) as batch_op:
        if 'order_details' in columns:
            batch_op.drop_column('order_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###
