"""discount added

Revision ID: 858e6beda012
Revises: c601ac6f9573
Create Date: 2024-11-13 18:44:50.009870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858e6beda012'
down_revision = 'c601ac6f9573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('discount')

    # ### end Alembic commands ###
