"""Main category

Revision ID: c25b3d5be4f7
Revises: 64aa44f9b825
Create Date: 2024-11-13 21:53:04.375906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25b3d5be4f7'
down_revision = '64aa44f9b825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maincategory', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('maincategory')

    # ### end Alembic commands ###
