"""Order table for Stripe

Revision ID: d749d8eff427
Revises: daa5558cf18d
Create Date: 2024-11-15 12:12:24.127367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd749d8eff427'
down_revision = 'daa5558cf18d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('quantity_of_each_order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_of_each_order', mysql.TEXT(), nullable=False))

    # ### end Alembic commands ###
