"""Order table for Stripe

Revision ID: daa5558cf18d
Revises: 5918508ae68e
Create Date: 2024-11-15 11:47:32.841620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'daa5558cf18d'
down_revision = '5918508ae68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [column['name'] for column in inspector.get_columns('orders')]
    if 'purchased_products' not in columns:
        with op.batch_alter_table('orders', schema=None) as batch_op:
            batch_op.add_column(sa.Column('purchased_products', sa.Text(), nullable=False))
            batch_op.drop_column('bought_products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bought_products', mysql.TEXT(), nullable=False))
        batch_op.drop_column('purchased_products')
    # ### end Alembic commands ###
