"""msg deleted

Revision ID: dd2d2b6c9c5e
Revises: aeb33ab3a805
Create Date: 2024-11-18 17:13:28.879899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd2d2b6c9c5e'
down_revision = 'aeb33ab3a805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_timestamp')

    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('recipient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name='messages_ibfk_1'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='messages_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
