"""init -todos-re

Revision ID: de64965f533f
Revises: 7630bab8ab9e
Create Date: 2024-10-25 20:00:48.037568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de64965f533f'
down_revision = '7630bab8ab9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=False))
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
