"""Order table for Stripe

Revision ID: e233dc898be0
Revises: 4fd4a7e14f92
Create Date: 2024-11-14 21:51:34.506251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e233dc898be0'
down_revision = '4fd4a7e14f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='product_categories_ibfk_1'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_categories_ibfk_2'),
    sa.PrimaryKeyConstraint('product_id', 'category_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
